version: '3.3'
services:
  posgresql:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'symfony'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
    volumes:
        - ./data/dump:/app/dump
        - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  php-fpm:
    image: webdevops/php-dev:7.3
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - posgresql
  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMNET_ROOT: /app/public
      WEB_DOCUMENT_INDEX: public/index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "80:80"
    volumes:
      - "./:/app"
    depends_on:
      - php-fpm
